@startuml
title CJM — Пользователь Авито.Кухня

start

:Открывает Авито.Кухня;

:Просматривает список заведений;

:Выбирает заведение;

:Изучает меню;

:Выбирает товар;

if (Товар доступен?) then (Да)


:Настраивает модификаторы;

:Добавляет товар в корзину;

:Оформляет заказ;

:Получает номер заказа;

:Отслеживает статус заказа;

if (Передумал до начала приготовления?) then (Да)

    :Отменяет заказ;

    stop

else (Нет)

    :Ожидает приготовление;

    :Ожидает доставку;

    :Получает заказ;

    stop

endif


else (Нет)

:Выбирает другой товар;
stop


endif

@enduml
